name: Publish new release to Docker hub

on:
  # push:
  #   branches:
  #     - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
    
      - name: Use Node.js 14.16.*
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.*
          
      - name: Install dependencies
        run: npm install
        
      - name: Lint
        run: npm run lint
      
      - name: Build
        run: npm run build -- --prod
        
      - name: Install forever
        run: npm install forever -g
      
      - name: Start app
        run: forever start node_modules/@angular/cli/bin/ng serve 
      
      - name: Sleep for 30 seconds (let the ng serve boot)
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
        
      - name: E2E
        run: npm run e2e:ci
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: newbuild
          path: /tmp/newbuild.tar
      

  use:
    runs-on: ubuntu-18.04
    needs: build
    steps:      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: newbuild
          path: /tmp
                
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: /tmp/newbuild.tar
          push: true
          tags: dennthrow/aci:latest
